### ISSUE TITLE
docker_registoryからimageの一覧の取得

### ISSUE THREAD

**Issue by Soto-soto** [takezyou/DigDog#11]

**Comment by Soto-soto** [comment]
- [ ] 1. docker_registryからimageを取得するAPIを探す．
- [ ] 2. 現状imageが1つしかなく検証できないので新規でimageをいくつか作成する．
- [ ] 3. rubyでAPIを作成する．

現状想定している作業はこんな感じ

**Comment by Soto-soto** [comment]
APIのdoc
https://docs.docker.com/registry/spec/api/

**Comment by Soto-soto** [comment]
最初に作成したDockerfileとimageがあるリポジトリ
https://gitlab.ie.u-ryukyu.ac.jp/gitlab/e175706/docker-test

**Comment by Soto-soto** [comment]
別のDockerfileとimageがあるリポジトリ
https://gitlab.ie.u-ryukyu.ac.jp/gitlab/e175706/docker-test-anothername

**Comment by Soto-soto** [comment]
docker_registryの設定のdoc
https://docs.docker.com/registry/configuration/#delete

**Comment by Soto-soto** [comment]
curl https://registry.ie.u-ryukyu.ac.jp/v2/_catalog
これでimageから取れます

**Comment by takezyou** [comment]
できたのでclose
