### ISSUE TITLE
docker-registryのアクセス制限問題

### ISSUE THREAD

**Issue by takezyou** [takezyou/DigDog#15]
今の所はそれほど必要ないが将来的にはアクセス制限をしないといけない問題がある。
gitlabのauthを使って解決できそう。
https://docs.gitlab.com/ee/administration/container_registry.html

**Comment by takezyou** [comment]
色々試したがうまくいかなかった．
再度調査するが，ある程度諦めるラインを決めないといけない．

**Comment by takezyou** [comment]
来週までやってできなかったら諦める

**Comment by takezyou** [comment]
ladpためす

**Comment by takezyou** [comment]
でけた。
gitlabが用意しているやつに変更したらできた。
ボリュームのマウント先変更したらおわりかな。
使いながら動作確認してく

**Comment by takezyou** [comment]
あとweb側のimageのリストの取得を高瀬にやってもらう

**Comment by hsrmy-ie** [comment]
[このコミット](https://github.com/takezyou/DigDog/pull/30/commits/ef0194cdbb302786977711d338877d8a5afa6baa)でpublicになっているリポジトリの一覧は取得できました

public、internal、privateのどの範囲まで取得できるようにするのか考えたほうがいいかもしれません

**Comment by takezyou** [comment]
とりあえず取得はできたので一旦閉じます．
細かい調整は余裕ができたらしましょう！
