### ISSUE TITLE
Kubernetesの調査と検証

### ISSUE THREAD

**Issue by takezyou** [takezyou/DigDog#2]
Kubernetesを触ったことないので実際に触ってみて使い方を学ぶ
環境構築してansibleを一応作るところまで

**Comment by takezyou** [comment]
https://qiita.com/mihirat/items/ebb0833d50c882398b0f
これのWelcome to nginxまでやってみた。
macのdocker for macで試しました。
やっぱりネットワーク周りが肝な気がする。
どう外部から接続するIPを振るかってところ

**Comment by takezyou** [comment]
https://qiita.com/nagase/items/15726e37057e7cc3b8cd
研究室のサーバーにkubernetes環境構築し直しました。
学内からであれば下記にアクセスすると少し触れる

```
hubris.ns.ie.u-ryukyu.ac.jp
impatience.ns.ie.u-ryukyu.ac.jp
laziness.ns.ie.u-ryukyu.ac.jp
```

**Comment by takezyou** [comment]
https://qiita.com/superbrothers/items/1822dbc5fc94e1ab5295
https://hackmd.io/pBWSHTFsRHit2Ayo0BmPVw?both

**Comment by Soto-soto** [comment]
https://k8sinfo.com/2019/02/13/create-k8s-environment-manual-1/
virtual box でのkubernetes構築方法

**Comment by takezyou** [comment]
とりあえずdex入れてldapでなんとなくloginできるところまでやった
ただ自由度がdex自体低そうなのでUAAを検討する
もう少し検証する必要ありそう
https://qiita.com/mamomamo/items/1651b8f9e44938c0de15
ここら辺も考えとかないといけない
