### ISSUE TITLE
RBACでkubectlで使えるコマンドを制限する

### ISSUE THREAD

**Issue by Soto-soto** [takezyou/DigDog#23]

**Comment by Soto-soto** [comment]
立ち上げられるpod台数を制限するために，webからしかpodを立ち上げられなくする．
そのユーザーが立ち上げたpodの台数はDBに保管する

**Comment by takezyou** [comment]
RBACの設定できたのでとりあえずそれでrailsに埋め込む作業をやります．

**Comment by takezyou** [comment]
railsに埋め込めた

**Comment by takezyou** [comment]
margeしたので閉じる
