### ISSUE TITLE
Dockerの勉強会資料を作成する

### ISSUE THREAD

**Issue by takezyou** [takezyou/DigDog#24]
10月のはじめくらいにdockerの勉強会をしたいのでそれの準備をする

**Comment by takezyou** [comment]
サイボウズの研修資料の中にあったのでそれを真似て作るのが良さそう

**Comment by takezyou** [comment]
https://speakerdeck.com/cybozuinsideout/2019-10-docker

**Comment by Soto-soto** [comment]
dockerについての勉強会をするなら内容は
- dockerについて
- VMとコンテナに違い
- dockerの使い方
これらは必要そうです
これ以外に要るものってあるでしょうか

**Comment by takezyou** [comment]
opensfit
docker swarmこんなのもある
dockerとk8sの違いをスライドに盛り込む

**Comment by takezyou** [comment]
アンケート作る
内容は考える

**Comment by takezyou** [comment]
こんなものを作っていますっていう説明を最初に入れる

**Comment by Soto-soto** [comment]
資料の話ではありませんが，勉強会を10/11(来週土曜日)に実施する．
そのためのconnpasの立ち上げと教室の予約を自分がやる

**Comment by takezyou** [comment]
資料作成は秋田
