### ISSUE TITLE
プログラミングコンテストの応募  資料作成

### ISSUE THREAD

**Issue by takezyou** [takezyou/DigDog#41]
11/11(月)までに提出する
プロコン発表資料

**Comment by Soto-soto** [comment]
作ってますます
https://docs.google.com/presentation/d/18YU7v9X-c3cQdbS1aiarkjChBv5x3x3CDUfttotjNDk/edit#slide=id.g741d7cdff6_0_20

**Comment by Soto-soto** [comment]
提出したのでcloseにします
