### ISSUE TITLE
domainのやつをrailsに組み込む

### ISSUE THREAD

**Issue by takezyou** [takezyou/DigDog#45]

**Comment by Soto-soto** [comment]
設計としてはAPIにドメインとサービス名を送れば
deploymentを作成してそれをapplyする感じになるかな．

**Comment by Soto-soto** [comment]
K8s::Resource的なものを使用してdeploymentを作成するのかな

**Comment by Soto-soto** [comment]
app/controllers/deploy_controller.rbにそれっぽいものがあったので一度それでやってみる

**Comment by Soto-soto** [comment]
ingress_controllerだとなんか別の意味になりそうだからdomain_controllerとして作成する

**Comment by takezyou** [comment]
mergeしたのでclose
