### ISSUE TITLE
kubectlが使えないと一部機能が使えない

### ISSUE THREAD

**Issue by hsrmy** [takezyou/DigDog#46]
kubectlが使えないと以下の機能が使えない
- exposeする際
- 初回ログイン時のnamespaceができない

**Comment by hsrmy-ie** [comment]
kubectlではなくapiを叩くように

**Comment by hsrmy-ie** [comment]
変更をPull Request #48 に出しておきました

**Comment by takezyou** [comment]
まーじしたのでクローズします。お疲れ様でした。
