### ISSUE TITLE
nginx-ingress-controllerを検証する

### ISSUE THREAD

**Issue by takezyou** [takezyou/DigDog#6]
お試しでドメインでアクセスできる用にするために使ってみる

**Comment by takezyou** [comment]
@Soto-soto これって結局試してないよね？？

**Comment by Soto-soto** [comment]
今日のタスクにしようかと思っていました…

**Comment by Soto-soto** [comment]
こちらの方を進めていました
https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/
nginx-ingress-controllerはk8s内部のip:portに名前を解釈する感じの流れになっていることを理解しました．
実際に使用する際のURLはhttp://なんとか(まだ使ってない沖縄の地名).ie.u-ryukyu.ac.jp/学籍番号/service名みたいな感じになりそう？

**Comment by takezyou** [comment]
了解です。
> URLはhttp://なんとか(まだ使ってない沖縄の地名).ie.u-ryukyu.ac.jp/学籍番号/service名みたいな感じになりそう？
http://(自由にする).st.ie.u-ryukyu.ac.jp　とかはできなさそう？？
DNSも設定必要そう

**Comment by takezyou** [comment]
https://github.com/kubernetes-incubator/external-dns
これで連携してドメイン登録できるかも必要はないかも

**Comment by takezyou** [comment]
@Soto-soto 
一応できた

DNSにはワイルドカードで設定を入れる
*  IN A 10.50.0.151 ingressコントローラーのipを加える
```
$ kubectl run echoheaders --image=gcr.io/google_containers/echoserver:1.4 --replicas=1 --port=8080
$  kubectl expose deployment echoheaders --port=80 --target-port=8080 --name=echoheaders --external-ip=10.50.0.151
$ cat echoheaders.yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo
spec:
  rules:
  - host: echo.ns.ie.u-ryukyu.ac.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: echoheaders
          servicePort: 80
```

これで好きなドメインでアクセス可能serviceportは常に80にしてtargetportをよしなに入れてもらうとよいかも

**Comment by takezyou** [comment]
そとの検証が終わったら一旦は検証を終了します。
負荷分散的なことは必要になったら考える。（多分よしなにやってくれると思うけど）

**Comment by takezyou** [comment]
さっき確認したらやっぱりうまくいってなかったので調査する

**Comment by Soto-soto** [comment]
今日はこれをする
https://developers.freee.co.jp/entry/kubernetes-ingress-controller

**Comment by Soto-soto** [comment]
https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/
ここの内容を上のやつに適用したらできました．

k8s側の設定はほとんど変更がなく，指定するIPもk8sで立っているingressのIP(固定値)なので，
比較的簡単にDNSサーバーに登録できそうです．

**Comment by Soto-soto** [comment]
今まではminikubeの方で構築をしていたので，オンプレの方で試してみる．
多分問題なくできると思う．

**Comment by Soto-soto** [comment]
問題なくオンプレの方でもできました．

**Comment by takezyou** [comment]
@Soto-soto いいすね！
今度確認したらcloseしましょう！

**Comment by Soto-soto** [comment]
検証自体は使用に問題がないことを確認したのでcloseとする．
